apiVersion: v1
kind: Pod
metadata:
  name: hostnameapp-manual-v2
  labels:
    creation_method: manual
    env: prod
spec:
  containers:
    - image: malcolmkee/hostname
      name:  hostname
      ports:
        - containerPort: 8080
          protocol: TCP