apiVersion: v1
kind: Pod
metadata:
  name: kubia-liveness
  labels:
    creation_method: manual
    env: prod
spec:
  containers:
    - image: luksa/kubia-unhealthy
      name:  kubia
      livenessProbe:
        httpGet:
          path: /
          port: 8080
        initialDelaySeconds: 15
        periodSeconds: 5
      ports:
        - containerPort: 8080
          protocol: TCP